language: android
jdk: oraclejdk8

# See https://github.com/travis-ci/travis-ci/issues/5582
sudo: required

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools

    - platform-tools
    - android-29
    - build-tools-29.0.2
    - extra-android-m2repository
    - extra-android-support

script: './gradlew clean build'